<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" PrivateAssets="all" />
    <ProjectReference Include="../../src/FCG.Catalog.Api/FCG.Catalog.Api.csproj" />
  </ItemGroup>
  <ItemGroup><Compile Include="../Shared/PedidoFakes.cs" Link="PedidoFakes.cs" /></ItemGroup>
</Project>
