<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" />
    <PackageReference Include="RabbitMQ.Client" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
    <ProjectReference Include="../FCG.Catalog.Application/FCG.Catalog.Application.csproj" />
    <ProjectReference Include="../FCG.Catalog.Domain/FCG.Catalog.Domain.csproj" />
  </ItemGroup>
</Project>
